### PR TITLE
Flatten and simplify core data structures. Simplify types.

### LINKED ISSUE #51: Flatten sparse values of vars and sparse weights of factors
Right now we use hash tables to keep those data:
https://github.com/HazyResearch/sampler/blob/master/src/factor.h#L339-L350
https://github.com/HazyResearch/sampler/blob/master/src/variable.h#L48-L50

They are not amenable to numba / numbskull, and may be sources of substantial overhead (not quantified yet..).

We may "flatten" them in these ways:

1. For var values, we keep a flat "value of var" array similar to the "var in factor" array. At load time, we translate all the "sparse values" in var assignments and factor specs into "dense indexes". That saves us from doing the `get_domain_index` lookups in critical paths. Additional overhead is one more `vov_offset` field in `Variable`.

2. For factor weights, we repurpose `CompactFactor` from one per var-tuple to one per var-value-tuple. Before, we'd use the `factor_params` lookup table to map each `CompactFactor` object to multiple weights (with `feature_value` inconsistently in both `FactorParams` and `CompactFactor`). After, each `CompactFactor` corresponds to exactly one `feature_value` and one `weight` and there is no need for lookup. We save those lookups and can simplify the grounding process (no need for agg). Space overhead is that we'd have a lot more `CompactFactor` objects.

At a high level, these seem quite feasible. If no one sees major issues, we can make these changes in DW and then corresponding changes in numbskull. Numbskull will then have support for sparse values and sparse weights (https://github.com/HazyResearch/numbskull/issues/37).

Thoughts?

### PR DESCRIPTION
**Pull request by alldefector**
Fixes #51 and #52 and #47

This is a major refactoring, removing a lot of complexity in the data structures; e.g.,
- `RawVariable, CompactFactor, RawFactor, CompactFactorGraph, FactorParam` are all gone now. 
- Also simplified types to use `size_t` for almost all non-enum integers (instead of the 16 aliases of uint64 and uint32). Wastes a bit space, but we can optimize that later...
- The new notion of `Factor` has a one to one correspondence to rows in DD's factor tables.
- The heavy `CompactFactor` index is replaced by 2-tier indexing: `Variable --FG.values--> VariableValue --FG.factor_index--> Factor`. `factor_index` is a simple int array.
- After loading, all var values (assignments and proposals) are "dense" now, saving the domain lookups.
- The input factor file format is also flat now; so no need for array aggs in grounding.

Some initial perf results on the chunking example (4K vars, 8M factors, 11M edges; on an MBP):
- Old: RAM = 945MB, 0.2 sec / learning epoch
- New: RAM = 714MB, 0.4 sec / learning epoch

So, despite using larger ints, RAM usage is actually reduced -- thanks to the removal of `CompactFactor[]`. This saving will become more prominent as a program involves more high-arity factors.

However, the 2-tier indexing seems to have caused the slow-down. This index structure may actually speed things up with sparse domain vars (which chunking doesn't have) and/or without word embeddings (which chunking has). I'll look into this and run more experiments to profile the perf changes.

### CODE REVIEW

**Comment by alldefector** [comment]
1. I'll leave it to the near future for type refining. If anyone is running a 32-bit machine, we should just throw up immediately...
2. RAM was measured during learning, so cleanup was done already.
3. They have different purposes and hence members: `VariableInFactor` is in a list ordered by factor and has `vid, var_domain_index` as members; `VariableValue` is in a list ordered by variable and has `var_domain_value, factor_index_base, factor_index_length` to index into the list of factor IDs (ie `factor_index`).
4. We did array_agg for categorical vars to collapse values, weights, and feature values onto distinct variable ID tuples.
5. The encoding handles booleans too -- they take one element in the `VariableValue` list.

**Comment by netj** [comment]
1. I think it's unhealthy/frustrating to completely collapse someone's careful effort on type disambiguation and just say we can bring it back later.  It's easy to increase the entropy but bringing back down is extremely hard.  We can get rid of less meaningful type aliases, e.g., num_*_t and *_id_t but throwing away the basic distinctions, e.g., between ids and values, is not quite acceptable for me.
2. I can confirm that.  It seems the STL map did have quite a bit of overhead then.  Booleans should now have some overhead at the cost of unifying the representation, and maybe we should also measure to see if that's negligible.
3. OK, I missed it's the other direction.  I wish the names were more intuitive, maybe like `VariableToFactor` and `FactorToVariable` instead of `VariableValue` and `VariableInFactor`, resp.
4. (not important) My point was each factor still corresponded to one aggregated row previously.  I guess you're emphasizing factor-weight correspondence.
5. I was talking about impact on performance for Booleans.

**Comment by alldefector** [comment]
More test results (old v new):

- examples/chunking (2K+2K words)
  - 4K vars, 8M factors
  - memory: 945MB v 714MB
  - learning epoch: 0.23s v 0.40s
  - infer epoch: 0.21s v 0.36s
- examples/census
  - 33K vars, 520K factors
  - memory: 100MB v 50MB
  - learning epoch: 0.019s v 0.024s
  - infer epoch: 0.008s v 0.017s
- memex1
  - 11M vars, 185M factors
  - memory: 120GB v 32GB
  - learning epoch: 6s v 4s
  - infer epoch: 4.3s v 3.6s
- memex2
  - 570K vars, 35M factors
  - memory: 6.7GB v 3.1GB
  - learning epoch: 0.72s v 0.35s
  - infer epoch: 0.81s v 0.46s

Conclusion: new version saves memory significantly (25% - 75% reduction) and on large graphs can be substantially faster.

**Comment by chrismre** [comment]
What about numbskull--have you tried the scaleout stuff there?

**Comment by alldefector** [comment]
Numbskull doesn't support sparse domains yet (which motivated this PR), but here are its numbers on census: 70MB memory, 0.12s / learning epoch, 0.02s / infer epoch. Actually, its data loading doesn't support factors with any categorical vars yet, so it crashes on the chunking example.

The distributed mode (https://github.com/HazyResearch/numbskull/blob/master/numbskull/distributed.py) seems broken -- `import gibbs` cannot be resolved. See also https://github.com/HazyResearch/numbskull/issues/1

**Comment by chrismre** [comment]
@bryan-he are the features above on your list? or no?

This seems much easier to add in to numbskull in a nice way... maybe it's time to take the lead there, @alldefector ?

**Comment by alldefector** [comment]
@chrismre Yeah, after landing this PR, I'll help numbskull to achieve feature parity with DW so we can benchmark (simple DW/NS toggle in DD). This weekend should be enough for that. Then I'll help with scaleout.

**Comment by bryan-he** [comment]
@alldefector Are there any other features that you still need? I can help on getting the DeepDive examples running.

**Comment by chrismre** [comment]
This is all awesome. 

@bryan-he make sure whatever @alldefector puts in, you can run the experiments you need for your paper :).

@alldefector 👍 Love if we can get something easier to wrap and setup on commodity clusters.

**Comment by netj** [comment]
@alldefector if the old code had memory leak because of fg.release() instead of .reset() potentially doubling the usage, it would be helpful to see the more accurate saving of the reorg excluding the leak

**Comment by chrismre** [comment]
+1

**Comment by alldefector** [comment]
@bryan-he If you could review this PR, make dataloading.py support domain loading (`dataloading.load_factors` probably works for categoricals automatically after this change but note the 4B to 8B changes for several fields) and domain value / index translation at loading time (see `FactorGraph::load_domains` and callers of `FactorGraph::get_var_value_at`), that'd be great. DD master is hooked with NS already. All you need to do is a smaller change to `deepdive.conf`, e.g., https://github.com/HazyResearch/deepdive/blob/master/examples/census/deepdive.conf.numbskull (you'd also need to run `pip install -e .` in NS repo first).

@chrismre @bryan-he  I'll do some research about distributed execution... what are the issues with `zmq` (ZeroMQ)? What other tools have you guys considered as good alternatives?

@netj I'll get some memory numbers for the old code with `.release` fixed. Just did the FactorToVariable and VariableToFactor name changes. For type aliases, the distinction b/w "id" and "value" isn't that clear when it comes to variable values because they are also value IDs... Can we land this for now, and I know someone who's expressed strong interest in contributing to DW and can use this for onboarding next week.

**Comment by alldefector** [comment]
@netj @chrismre Memory usage for old sampler with `fg.release` replaced by `fg.reset` (https://github.com/HazyResearch/sampler/blob/master/src/dimmwitted.cc#L83):

- chunking: 665MB (peak is still about 900MB)
- census: 100MB (somehow same as before; maybe below certain reclaim threshold)

@xiaoling @raphaelhoff Could you make the same one-line change in DD master (inference/dimmwitted/src/dimmwitted.cc) and re-measure mem usage of the above `memex1` and `memex2` workloads?

**Comment by raphaelhoff** [comment]
@alldefector @netj On memex2 (location entity linking), changing `fg.release` to `fg.reset` saves some memory: 6.2GB (`fg.reset`) vs 6.7GB (`fg.release`).

**Comment by alldefector** [comment]
Got LGTM from @netj. Landing now to unblock NS dev.

**Pull request merged**
